### PR TITLE
Create CreatingNewVentures.md

### PR DESCRIPTION
**Pull request by dbaicker**
I am creating a new branch!

### CODE REVIEW

**Comment by dbaicker** [comment]
Hey team, I put this together with some of my key takeaways for lean startups in tech and building partial prototypes.  @SamStrauss @laidem, what do you guys think?  Do you remember anything that I missed?

**Comment by SamStrauss** [comment]
@dbaicker I think this looks great :+1: .  I didn't know you were such a big parks and rec fan.  Jean-Ralphio is the WORST!

**Comment by laidem** [comment]
@dbaicker looks fantastic!! :+1: thanks for sharing these tips

**Comment by SamStrauss** [comment]
:+1:

Samantha Strauss
Columbia MBA '16
sstrauss16@gsb.columbia.edumailto:sstrauss16@gsb.columbia.edu
(214) 213-2215

On Apr 23, 2015, at 11:16 PM, dmordente <notifications@github.com<mailto:notifications@github.com>> wrote:

Merged #5https://github.com/dmordente/lessons-learned/pull/5.

**Pull request merged**
