### PR TITLE
SpecifyingSoftware1

### PR DESCRIPTION
**Pull request by rbreitenwischer**
Check out my new article on how to specify software

### CODE REVIEW

**Comment by rbreitenwischer** [comment]
@SamStrauss Can you take a look at this and provide feedback?

**Comment by SamStrauss** [comment]
@rbreitenwischer This looks great but can you add some spacing to make it easier to read please! :100:

**Comment by SamStrauss** [comment]
Love the changes looks good to go! :+1:

**Comment by dmordente** [comment]
Great job :+1:

**Pull request merged**
