### PR TITLE
MobileAppDevDecisions

### PR DESCRIPTION
**Pull request by dmordente**
This page describes factors to consider when developing a mobile application.

### CODE REVIEW

**Comment by dmordente** [comment]
Hi Team! What do you think about my thoughts on mobile application development @bbrooksby and @rbreitenwischer  . Thanks for your input!

**Comment by rbreitenwischer** [comment]
@dmordente this looks great - but maybe break the first paragraph up into two paragraphs so its easier to read.  :100:

**Comment by rbreitenwischer** [comment]
@dmordente looks rockin! :+1:

**Comment by bbrooksby** [comment]
I think this looks fantastic. :+1: 
Alt Text

**Comment by dmordente** [comment]
Thanks, guys! Merging pull request based on the :+1:s

**Pull request merged**
