### PR TITLE
Create Hiring_a_software_engineer.md

### PR DESCRIPTION
**Pull request by bbrooksby**
This page describes useful questions to ask a would-be software engineering hire.

### CODE REVIEW

**Comment by bbrooksby** [comment]
Hi team, @dmordente and @rbreitenwischer - what do you think of this article. I for one, found the developer photo quite fetching.

**Comment by dmordente** [comment]
@bbrooksby Looks great! When asking your questions to software engineers, can you explicitly call out their approach to continuous improvement?

**Comment by bbrooksby** [comment]
Great suggestion @dmordente You are a real asset to this incredible team. @peterbell would be so proud of us,

**Comment by rbreitenwischer** [comment]
@bbrooksby this is really great!  I like that you provided the example questions to ask.  Maybe add one more question?

**Comment by bbrooksby** [comment]
Thanks for the feedback guys @dmordente  and @rbreitenwischer . I have included your suggestions. Please give me a thumbs up if you think we are ready to :shipit:

**Comment by dmordente** [comment]
@bbrooksby :+1: Good to go!

**Comment by rbreitenwischer** [comment]
:+1: good to go @bbrooksby

**Comment by bbrooksby** [comment]
Awesome. Take that haters.

Alt Text

Thanks guys, lets :shipit:

**Pull request merged**
